import {
  AlertTriangle, ArrowLeft, ArrowRight, ArrowRightLeft, BookOpen, Bot, BotMessageSquare, Brain,
  Calendar, Check, CheckCircle2, ChevronDown, ChevronRight, ChevronUp, Clock,
  Copy, Download, Eraser, ExternalLink, Eye, EyeOff, FileBarChart, FileText, Filter,
  Grid3x3, History, Info, LayoutDashboard, LightbulbIcon,
  List, Loader2, Lock, Maximize2, MessageSquare, MessageSquareShare, Mic, MicOff,
  Minimize2, Minus, Monitor, MonitorSmartphone, MoreVertical, Network,
  Pause, Pencil, Pin, Play, Plus, RefreshCw, ScreenShare, Search, Send,
  Settings, ShieldCheck, Sparkles, Square, Stethoscope, Tag,
  Target, Trash2, User, Users, Workflow, Wrench, X, ZapIcon,
} from 'lucide-react'

const ICONS = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-left': ArrowRightLeft,
  'book-open': BookOpen,
  'bot': Bot,
  'bot-message-square': BotMessageSquare,
  'brain': Brain,
  'calendar': Calendar,
  'check': Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clock': Clock,
  'copy': Copy,
  'download': Download,
  'eraser': Eraser,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-bar-chart': FileBarChart,
  'file-text': FileText,
  'filter': Filter,
  'grid-3x3': Grid3x3,
  'history': History,
  'info': Info,
  'layout-dashboard': LayoutDashboard,
  'lightbulb': LightbulbIcon,
  'list': List,
  'loader-2': Loader2,
  'lock': Lock,
  'maximize-2': Maximize2,
  'message-square': MessageSquare,
  'message-square-share': MessageSquareShare,
  'mic': Mic,
  'mic-off': MicOff,
  'minimize-2': Minimize2,
  'minus': Minus,
  'monitor': Monitor,
  'monitor-smartphone': MonitorSmartphone,
  'more-vertical': MoreVertical,
  'network': Network,
  'pause': Pause,
  'pencil': Pencil,
  'pin': Pin,
  'play': Play,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'screen-share': ScreenShare,
  'search': Search,
  'send': Send,
  'settings': Settings,
  'shield-check': ShieldCheck,
  'sparkles': Sparkles,
  'square': Square,
  'stethoscope': Stethoscope,
  'tag': Tag,
  'target': Target,
  'trash-2': Trash2,
  'user': User,
  'users': Users,
  'workflow': Workflow,
  'wrench': Wrench,
  'x': X,
  'zap': ZapIcon,
}

export default function Icon({ name, size = 16, className, style }) {
  const Comp = ICONS[name]
  if (!Comp) return null
  return <Comp size={size} className={className} style={style} />
}
